---

# This project is a mix of languages; default to bash for now
language: bash

install:
  # Install yamllint for testing YAML files (including Ansible)
  - pip install --user yamllint
  # Install ansible-lint for testing Ansible scripts
  - pip install --user ansible-lint

script:
  # Validate our Ansible playbooks
  - python -myamllint -f parsable *-playbook.yml
  - ansible-lint -p *-playbook.yml
  # Validate the quickstart shell scripts
  - shellcheck -f gcc quickstart
  # Validate the shell scripts for aws/machine
  - pushd aws/machine ; find . \( -name \*.sh -or -name \*.bash \) -exec shellcheck -x -f gcc {} + ; popd
  # TODO Add additional validation/build steps here

notifications:
  email: false

