---

#
# Builds supporting RDSS Archivematica images used for QA and publishes them to
# the given Docker registry.
#
# Usage:
#
#     $ ansible-playbook publish-qa-images-playbook.yml \
#           --extra-vars="registry=aws_account_id.dkr.ecr.region.amazonaws.com/"
#

- hosts: "localhost"
  connection: "local"

  vars:
    repos:
      - name: "RDSS Archivematica Channel Adapter"
        repo: "https://github.com/JiscRDSS/rdss-archivematica-channel-adapter"
        version: "v0.2.6"
        dest: "./src/rdss-archivematica-channel-adapter"
      - name: "RDSS Archivematica MsgCreator"
        repo: "https://github.com/JiscRDSS/rdss-archivematica-msgcreator"
        version: "v0.1.0-rc.1"
        dest: "./src/rdss-archivematica-msgcreator"
    images:
      - name: "{{ registry }}rdss-archivematica-msgcreator"
        dockerfile: "Dockerfile"
        path: "./src/rdss-archivematica-msgcreator/"
        tag: "v0.1.0-rc.1"
      - name: "{{ registry }}dynalite"
        path: "./src/rdss-archivematica-channel-adapter/hack/minikine"
        dockerfile: "dynalite.Dockerfile"
        tag: "v0.2.6"
      - name: "{{ registry }}minikine"
        path: "./src/rdss-archivematica-channel-adapter/hack/minikine"
        dockerfile: "minikine.Dockerfile"
        tag: "v0.2.6"


  tasks:

    - name: "Ensure that the variable registry is defined"
      fail:
        msg: "Variable registry is undefined"
      when: "registry is not defined"

    - name: "Install playbook dependencies"
      pip:
        name: "{{ item }}"
        extra_args: "--user"
      with_items:
        - "setuptools"
        - "docker"

    - name: "Clone repositories"
      git:
        accept_hostkey: "yes"
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      with_items: "{{ repos }}"

    - name: "Build and tag images"
      command: docker build \
        -t "{{ item.name }}:{{ item.tag }}" \
        -t "{{ item.name }}:latest" \
        -f "{{ item.dockerfile }}" .
      args:
        chdir: "{{ item.path }}"
      with_items: "{{ images }}"

    - name: "Publish images"
      command: docker push "{{ item.name }}"
      with_items: "{{ images }}"
