---

#
# Builds core RDSS Archivematica images intended for production deployment and
# publishes them to the given Docker registry.
#
# Usage:
#
#     $ ansible-playbook publish-images-playbook.yml \
#           --extra-vars="registry=aws_account_id.dkr.ecr.region.amazonaws.com/"
#

- hosts: "localhost"
  connection: "local"

  vars:
    repos:
      - name: "Archivematica repository"
        repo: "https://github.com/JiscRDSS/archivematica"
        version: "v0.1.0-rc.1"
        dest: "./src/archivematica"
      - name: "Archivematica Storage Service repository"
        repo: "https://github.com/JiscRDSS/archivematica-storage-service"
        version: "v0.1.0-rc.1"
        dest: "./src/archivematica-storage-service"
      - name: "RDSS Archivematica Automation Tools"
        repo: "https://github.com/JiscRDSS/rdss-archivematica-automation-tools.git"
        version: "v0.1.0-rc.1"
        dest: "./src/rdss-archivematica-automation-tools"
      - name: "RDSS Archivematica Channel Adapter"
        repo: "https://github.com/JiscRDSS/rdss-archivematica-channel-adapter"
        version: "v0.2.6"
        dest: "./src/rdss-archivematica-channel-adapter"
      - name: "RDSS Arkivum NextCloud"
        repo: "https://github.com/JiscRDSS/rdss-arkivum-nextcloud"
        version: "v0.1.0-rc.1"
        dest: "./src/rdss-arkivum-nextcloud"
        make_target: "build-files-move-app"
    images:
      - name: "{{ registry }}archivematica-automation-tools"
        dockerfile: "Dockerfile"
        path: "./src/rdss-archivematica-automation-tools/"
        tag: "v0.1.0-rc.1"
      - name: "{{ registry }}archivematica-mcp-server"
        path: "./src/archivematica/src/"
        dockerfile: "MCPServer.Dockerfile"
        tag: "v0.1.0-rc.1"
      - name: "{{ registry }}archivematica-mcp-client"
        path: "./src/archivematica/src/"
        dockerfile: "MCPClient.Dockerfile"
        tag: "latest"
      - name: "{{ registry }}archivematica-dashboard"
        path: "./src/archivematica/src/"
        dockerfile: "dashboard.Dockerfile"
        tag: "v0.1.0-rc.1"
      - name: "{{ registry }}archivematica-storage-service"
        path: "./src/archivematica-storage-service/"
        dockerfile: "Dockerfile"
        tag: "v0.1.0-rc.1"
      - name: "{{ registry }}rdss-archivematica-channel-adapter"
        dockerfile: "Dockerfile"
        path: "./src/rdss-archivematica-channel-adapter/"
        tag: "v0.2.6"
      - name: "{{ registry }}nextcloud"
        dockerfile: "Dockerfile"
        path: "./src/rdss-arkivum-nextcloud/"
        tag: "v0.1.0-rc.1"

  tasks:

    - name: "Ensure that the variable registry is defined"
      fail:
        msg: "Variable registry is undefined"
      when: "registry is not defined"

    - name: "Install playbook dependencies"
      pip:
        name: "{{ item }}"
        extra_args: "--user"
      with_items:
        - "setuptools"
        - "docker"

    - name: "Clone repositories"
      git:
        accept_hostkey: "yes"
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      with_items: "{{ repos }}"

    - name: "Prepare source"
      make:
        chdir: "{{ item.dest }}"
        target: "{{ item.make_target}}"
      when: "item.make_target is defined"
      with_items: "{{ repos }}"

    - name: "Build and tag images"
      command: docker build \
        -t "{{ item.name }}:{{ item.tag }}" \
        -t "{{ item.name }}:latest" \
        -f "{{ item.dockerfile }}" .
      args:
        chdir: "{{ item.path }}"
      with_items: "{{ images }}"

    - name: "Publish images"
      command: docker push "{{ item.name }}"
      with_items: "{{ images }}"
