---
version: "2"

volumes:

  ldap_data:

  idp_credentials:
  idp_logs:

services:

  # Override main nginx config, linking it to our demo services
  nginx:
    image: "arkivum/shibboleth-nginx"
    container_name: "myapp.${DOMAIN_NAME}"
    hostname: "myapp"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "default"
      - "example"
    environment:
      # Client app configuration
      CLIENT_APP_HOSTNAME: "myapp.${DOMAIN_NAME}"
      #CLIENT_APP_SECURE_PATH: "/app"

      # Nginx proxying - the actual app we want to present
      NGINX_PROXY_DESTINATION: "http://example-app:8000"

      # Shibboleth config
      SHIBBOLETH_IDP_ENTITY_ID: "https://idp.${DOMAIN_NAME}/idp/shibboleth"
      SHIBBOLETH_IDP_METADATA_URL: "https://idp.${DOMAIN_NAME}:4443/idp/shibboleth"
    expose:
      - "443"
    ports:
      - "${NGINX_EXTERNAL_IP}:443:443"
    depends_on:
      - "example-app"
    links:
      - "example-app"
      - "example-idp:idp.${DOMAIN_NAME}"

  # LDAP service for the given domain
  example-ldap:
    image: "arkivum/example-ldap"
    container_name: "ldap.${DOMAIN_NAME}"
    hostname: "ldap"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "example"
    environment:
      - "LDAP_DOMAIN=${DOMAIN_NAME}"
      - "LDAP_ORGANISATION=Example University"
      - "LDAP_TLS=false"
    volumes:
      - "ldap_data:/var/lib/ldap/"
    expose:
      - "389"

  # Shibboleth IdP service for the domain
  example-idp:
    image: "arkivum/example-shib-idp"
    container_name: "idp.${DOMAIN_NAME}"
    hostname: "idp"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "example"
    environment:
      - "JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=12345"
      - "JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=12345"
    volumes:
      - "idp_credentials:/opt/shibboleth-idp/credentials"
      - "idp_logs:/opt/shibboleth-idp/logs"
    expose:
      - "4443"
      - "8443"
    ports:
      - "${IDP_EXTERNAL_IP}:443:4443"
    depends_on:
      - "example-ldap"
      - "example-sp"
    links:
      - "example-ldap:ldap.${DOMAIN_NAME}"
      - "example-sp:sp1.${DOMAIN_NAME}"

  # Demo Shibboleth SP for the given domain, which uses djangosaml2
  example-sp:
    image: "arkivum/example-shib-sp"
    container_name: "sp1.${DOMAIN_NAME}"
    hostname: "sp1"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "example"
    expose:
      - "80"
    ports:
      - "${SP1_EXTERNAL_IP}:80:80"
    links:
      - "example-ldap:ldap.${DOMAIN_NAME}"

  # Demo app, which relies on nginx-shibboleth for auth
  example-app:
    image: "alang/django:1.8-python2"
    networks:
      - "example"
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_APP: "myapp"
      FORWARDED_ALLOW_IPS: "*"  # Specific to Gunicorn
      GUNICORN_CMD_ARGS: "--bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level info"
      PYTHONUNBUFFERED: "1"
    volumes:
      - "./myapp/src/myapp/:/usr/django/app/"
    expose:
      - "8000"

networks:
  example:
    driver: "bridge"
