---
version: "2"

services:

  # Override main nginx config, enabling Shibboleth for Archivematica services
  # which both run on port 443
  nginx:
    image: "arkivum/shibboleth-nginx:${DOMAIN_NAME}"
    build:
      context: "./am-shib/nginx/"
      args:
        - DOMAIN_NAME
        - NGINX_CONF_TEMPLATE_FILE=templates/am-shib.conf.tpl
        - SHIBBOLETH_ATTRCHECKER_TEMPLATE_FILE=templates/attrChecker.html.tpl
        - SHIBBOLETH_CONF_TEMPLATE_FILE=templates/shibboleth2.xml.tpl
    networks:
      default:
          aliases:
            - "dashboard.archivematica.${DOMAIN_NAME}"
            - "ss.archivematica.${DOMAIN_NAME}"
      shibnet:
          aliases:
            - "dashboard.archivematica.${DOMAIN_NAME}"
            - "ss.archivematica.${DOMAIN_NAME}"

    environment:
      # The hostname of the nginx server serving Archivematica
      AM_DASHBOARD_HOST: "dashboard.archivematica.${DOMAIN_NAME}"
      AM_STORAGE_SERVICE_HOST: "ss.archivematica.${DOMAIN_NAME}"
      # Shibboleth FastCGI SP config
      SHIBBOLETH_IDP_ENTITY_ID: "https://idp.${DOMAIN_NAME}/idp/shibboleth"
      SHIBBOLETH_IDP_METADATA_URL: "https://idp.${DOMAIN_NAME}:${IDP_EXTERNAL_PORT}/idp/shibboleth"
      # Deployment settings
      AM_EXTERNAL_PORT:
    volumes:
      #
      # Nginx
      #
      # Add Shibboleth FastCGI config
      - "${VOL_BASE}/am-shib/etc/nginx/shib_clear_headers:/etc/nginx/shib_clear_headers:ro"
      - "${VOL_BASE}/am-shib/etc/nginx/shib_fastcgi_params:/etc/nginx/shib_fastcgi_params:ro"
      # Override the default nginx archivematica config with ones for Shibboleth
      - "${VOL_BASE}/am-shib/etc/nginx/archivematica.conf:/etc/nginx/conf.d/archivematica.conf:ro"
      - "${VOL_BASE}/am-shib/etc/nginx/am-shib.inc:/etc/nginx/conf.d/am-shib.inc:ro"
      #
      # Shibboleth
      #
      # Add Shibboleth customizations
      - "${VOL_BASE}/am-shib/etc/sp/attribute-map.xml:/etc/shibboleth/attribute-map.xml:ro"
      - "${VOL_BASE}/am-shib/etc/sp/attribute-policy.xml:/etc/shibboleth/attribute-policy.xml:ro"
      - "${VOL_BASE}/am-shib/etc/sp/attrChecker.pl:/etc/shibboleth/attrChecker.pl:ro"
      - "${VOL_BASE}/am-shib/etc/sp/console.logger:/etc/shibboleth/console.logger:ro"
      - "${VOL_BASE}/am-shib/etc/sp/security-policy.xml:/etc/shibboleth/security-policy.xml:ro"
      - "${VOL_BASE}/am-shib/etc/sp/shibd.logger:/etc/shibboleth/shibd.logger"
      #
      # Supervisor
      #
      # Override the default Supervisor config to add additional programs
      - "${VOL_BASE}/am-shib/etc/supervisor/shibboleth.conf:/etc/supervisor/conf.d/shibboleth.conf:ro"
      #
      # Secrets
      #
      - "${VOL_BASE}/am-shib/build/secrets/:/secrets/:ro"
      #
      # Bootstrap
      #
      - "${VOL_BASE}/am-shib/nginx/bootstrap.sh:/usr/sbin/bootstrap.sh:ro"
    command: ["/usr/local/bin/ep",
      "-v", "/etc/nginx/conf.d/am-shib.conf", "/etc/shibboleth/shibboleth2.xml",
      "--",
      "/bin/sh", "-c",
      "bootstrap.sh && /usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf"
    ]
    expose:
      - "443"
    ports:
      - "${NGINX_EXTERNAL_IP}:${AM_EXTERNAL_PORT}:443"
    depends_on:
      - "archivematica-dashboard"
      - "archivematica-storage-service"

  archivematica-dashboard:
    environment:
      ARCHIVEMATICA_DASHBOARD_SHIBBOLETH_AUTHENTICATION: "True"

  archivematica-storage-service:
    environment:
      SS_SHIBBOLETH_AUTHENTICATION: "True"

networks:
  shibnet:
    driver: "bridge"