---
version: "2"

#
# Dev environment configuration for RDSSARK services
#
# This compose file is intended to be used with docker-compose.qa.yml, the
# definitions here just add build config.
#

services:

  dynalite:
    build:
      context: "../src/rdss-archivematica-channel-adapter/hack/minikine"
      dockerfile: "dynalite.Dockerfile"

  minikine:
    build:
      context: "../src/rdss-archivematica-channel-adapter/hack/minikine"
      dockerfile: "minikine.Dockerfile"

  archivematica-automation-tools:
    build: '../src/rdss-archivematica-automation-tools/'

  archivematica-mcp-server:
    build:
      context: "../src/archivematica/src"
      dockerfile: "MCPServer.Dockerfile"

  archivematica-mcp-client:
    build:
      context: "../src/archivematica/src"
      dockerfile: "MCPClient.Dockerfile"

  archivematica-dashboard:
    build:
      context: "../src/archivematica/src"
      dockerfile: "dashboard.Dockerfile"

  archivematica-storage-service:
    build:
      context: "../src/archivematica-storage-service"

  rdss-archivematica-channel-adapter-consumer:
    build:
      context: "../src/rdss-archivematica-channel-adapter"

  rdss-archivematica-channel-adapter-publisher:
    build:
      context: "../src/rdss-archivematica-channel-adapter"

  rdss-archivematica-msgcreator:
    build:
      context: "../src/rdss-archivematica-msgcreator"
