version: '2'

volumes:

  # Named external volumes for NextCloud external storage locations for RDSS
  archivematica_pipeline_data:
    external:
      name: "rdss_am-pipeline-data"
  archivematica_storage_service_location_data:
    external:
      name: "rdss_am-ss-location-data"
  arkivum-storage:
    external:
      name: "rdss_arkivum-storage"
  jisc-test-research-data:
    external:
      name: "rdss_jisc-test-research-data"
  mysql_data:
    external:
      name: "rdss_mysql_data"
  nextcloud_data:
    external:
      name: "rdss_nextcloud-data"
  nextcloud_themes:
    external:
      name: "rdss_nextcloud-themes"

services:

  # This is a duplicate definition of the `mysql` service from the qa compose
  # config. We could just use that, however that requires us to depend on the
  # qa config, which isn't right in all circumstances. Therefore we repeat the
  # definition, and if the qa config is also included then only one instance
  # will be created.
  mysql:
    image: "percona:5.6"
    user: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - "${VOL_BASE}/dev/etc/mysql/my.cnf:/etc/mysql/my.cnf:ro"
      - "mysql_data:/var/lib/mysql"
    expose:
      - "3306"

  # This is a duplicate definition of the `redis` service from the qa compose
  # config. We could just use that, however that requires us to depend on the
  # qa config, which isn't right in all circumstances. Therefore we repeat the
  # definition, and if the qa config is also included then only one instance
  # will be created.
  redis:
      image: "redis:3.2-alpine"
      command: '--save "" --appendonly no'  # Persistency disabled
      user: "redis"
      expose:
        - "6379"

  nextcloud:
    image: "nextcloud"
    build:
      context: "../src/rdss-arkivum-nextcloud/"
    hostname: "nextcloud"
    domainname: "${DOMAIN_NAME}"
    environment:
      ADMIN_USER: "astoradmin"
      ADMIN_PASSWORD: "arkivum"
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASSWORD: "12345"
      DB_PORT: "3306"
      DB_TYPE: "mysql"
      GID: "${NEXTCLOUD_RUNAS_GID}"
      UID: "${NEXTCLOUD_RUNAS_UID}"
      EXTERNAL_STORAGES: "archivematica-aips:/mnt/am-pipeline-data/www/AIPsStore \
        archivematica-dips:/mnt/am-pipeline-data/www/DIPsStore \
        archivematica-processing-config:/mnt/am-pipeline-data/sharedMicroServiceTasksConfigs/processingMCPConfigs \
        arkivum-storage:/mnt/astor/aipingest \
        automated-transfer:/mnt/am-ss-default-location-data/automated \
        interactive-transfer:/mnt/am-ss-default-location-data/interactive \
        s3-jisc-test-research:/mnt/jisc-test-research-data"
    volumes:
      # Nextcloud app volumes
      - "nextcloud_data:/var/lib/nextcloud"
      - "nextcloud_themes:/nextcloud/themes"
      # External storage locations
      - "archivematica_pipeline_data:/mnt/am-pipeline-data"
      - "archivematica_storage_service_location_data:/mnt/am-ss-default-location-data"
      - "arkivum-storage:/mnt/astor/"
      - "jisc-test-research-data:/mnt/jisc-test-research-data"
    ports:
      - "${NEXTCLOUD_EXTERNAL_IP}:${NEXTCLOUD_EXTERNAL_PORT}:8888"
    depends_on:
      - "mysql"
      - "redis"
    links:
      - "mysql"
      - "redis"
