---
version: "2"

volumes:

  ldap_data:

  idp_credentials:
  idp_logs:

services:

  # Shibboleth IdP service for the domain
  idp:
    image: "arkivum/shibboleth-idp:${DOMAIN_NAME}"
    build:
      context: "./shib/idp/"
      args:
        - DOMAIN_NAME
    container_name: "idp.${DOMAIN_NAME}"
    hostname: "idp"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "shibnet"
    environment:
      - "JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=12345"
      - "JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=12345"
    volumes:
      - "idp_credentials:/opt/shibboleth-idp/credentials"
      - "idp_logs:/opt/shibboleth-idp/logs"
      # Provide our own IdP metadata file, configured for our SPs
      - "./example-shib/idp/build/metadata-providers.xml:/opt/shibboleth-idp/conf/metadata-providers.xml:ro"
    expose:
      - "4443"
      - "8443"
    ports:
      - "${IDP_EXTERNAL_IP}:443:4443"
    depends_on:
      - "example-sp"
      - "ldap"
    links:
      - "example-sp:sp1.${DOMAIN_NAME}"
      - "ldap:ldap.${DOMAIN_NAME}"

  # LDAP service for the given domain
  ldap:
    image: "osixia/openldap"
    hostname: "ldap"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "shibnet"
    environment:
      - "LDAP_DOMAIN=${DOMAIN_NAME}"
      - "LDAP_ORGANISATION=${DOMAIN_ORGANISATION}"
      - "LDAP_TLS=false"
    volumes:
      - "ldap_data:/var/lib/ldap/"
      - "./shib/ldap/etc/ldap/edu/:/usr/local/ldap/edu/"
      - "./shib/ldap/build/demo-users.ldif:/usr/local/ldap/demo-users.ldif:ro"
    expose:
      - "389"

  # Override main nginx config, linking it to our demo services
  nginx:
    image: "arkivum/shibboleth-nginx:${DOMAIN_NAME}"
    container_name: "myapp.${DOMAIN_NAME}"
    hostname: "myapp"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "default"
      - "shibnet"
    environment:
      # Client app configuration
      CLIENT_APP_HOSTNAME: "myapp.${DOMAIN_NAME}"
      #CLIENT_APP_SECURE_PATH: "/app"

      # Nginx proxying - the actual app we want to present
      NGINX_PROXY_DESTINATION: "http://example-app:8000"

      # Shibboleth config
      SHIBBOLETH_IDP_ENTITY_ID: "https://idp.${DOMAIN_NAME}/idp/shibboleth"
      SHIBBOLETH_IDP_METADATA_URL: "https://idp.${DOMAIN_NAME}:4443/idp/shibboleth"
    expose:
      - "443"
    ports:
      - "${NGINX_EXTERNAL_IP}:443:443"
    depends_on:
      - "example-app"
    links:
      - "example-app"
      - "idp:idp.${DOMAIN_NAME}"

  # Demo Shibboleth SP for the given domain, which uses djangosaml2
  example-sp:
    image: "arkivum/example-shib-sp"
    build:
      context: "./example-shib/sp/"
      args:
        - DOMAIN_NAME
    container_name: "sp1.${DOMAIN_NAME}"
    hostname: "sp1"
    domainname: "${DOMAIN_NAME}"
    networks:
      - "shibnet"
    expose:
      - "80"
    ports:
      - "${SP1_EXTERNAL_IP}:80:80"

  # Demo app, which relies on nginx-shibboleth for auth
  example-app:
    image: "alang/django:1.8-python2"
    networks:
      - "shibnet"
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_APP: "myapp"
      FORWARDED_ALLOW_IPS: "*"  # Specific to Gunicorn
      GUNICORN_CMD_ARGS: "--bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level info"
      PYTHONUNBUFFERED: "1"
    volumes:
      # Use of BASE_DIR is necessary here because compose gets incorrect context
      # when using config file from outside of same directory (e.g. parent dir)
      - "./example-shib/myapp/src/myapp/:/usr/django/app/:ro"
    expose:
      - "8000"

networks:
  shibnet:
    driver: "bridge"
