---
version: "2"

#
# Dev environment configuration for RDSSARK services
#
# This compose file is intended to be used with docker-compose.qa.yml, the
# definitions here just add build config.
#

services:

  dynalite:
    build:
      context: "../src/rdss-archivematica-channel-adapter/hack/minikine"
      dockerfile: "dynalite.Dockerfile"

  archivematica-automation-tools:
    build: '../src/rdss-archivematica-automation-tools/'

  archivematica-mcp-server:
    build:
      context: "../src/archivematica/src"
      dockerfile: "MCPServer.Dockerfile"
    volumes:
      - "${VOL_BASE}/../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "${VOL_BASE}/../src/archivematica/src/dashboard/:/src/dashboard/"
      - "${VOL_BASE}/../src/archivematica/src/MCPServer/:/src/MCPServer/"

  archivematica-mcp-client:
    build:
      context: "../src/archivematica/src"
      dockerfile: "MCPClient.Dockerfile"
      args:
        ARCHIVEMATICA_VERSION: "${VERSION}"
        AGENT_CODE: "${VERSION}"
    volumes:
      - "${VOL_BASE}/../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "${VOL_BASE}/../src/archivematica/src/dashboard/:/src/dashboard/"
      - "${VOL_BASE}/../src/archivematica/src/MCPClient/:/src/MCPClient/"

  archivematica-dashboard:
    build:
      context: "../src/archivematica/src"
      dockerfile: "dashboard.Dockerfile"
      args:
        ARCHIVEMATICA_VERSION: "${VERSION}"
        AGENT_CODE: "${VERSION}"
    volumes:
      - "${VOL_BASE}/../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "${VOL_BASE}/../src/archivematica/src/dashboard/:/src/dashboard/"

  archivematica-storage-service:
    build:
      context: "../src/archivematica-storage-service"
    volumes:
      - "${VOL_BASE}/../src/archivematica-storage-service/:/src/"

  rdss-archivematica-channel-adapter-consumer:
    build:
      context: "../src/rdss-archivematica-channel-adapter"
    entrypoint: "go run main.go consumer"
    volumes:
      - "${VOL_BASE}/../src/rdss-archivematica-channel-adapter:/go/src/github.com/JiscRDSS/rdss-archivematica-channel-adapter"

  rdss-archivematica-channel-adapter-publisher:
    build:
      context: "../src/rdss-archivematica-channel-adapter"
    entrypoint: "go run main.go publisher"
    volumes:
      - "${VOL_BASE}/../src/rdss-archivematica-channel-adapter:/go/src/github.com/JiscRDSS/rdss-archivematica-channel-adapter"

  rdss-archivematica-msgcreator:
    build:
      context: "../src/qa/rdss-archivematica-msgcreator"
    entrypoint: "go run main.go -addr=0.0.0.0:8000 -prefix=/msgcreator -kinesis-endpoint='${RDSS_ADAPTER_KINESIS_ENDPOINT}' -kinesis-stream=main -kinesis-region='${RDSS_ADAPTER_KINESIS_AWS_REGION}'-s3-access-key=AKIAIOSFODNN7EXAMPLE -s3-secret-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -s3-region=eu-west-2 -s3-endpoint=https://minio:9000"
    volumes:
      - "${VOL_BASE}/../src/qa/rdss-archivematica-msgcreator:/go/src/github.com/JiscRDSS/rdss-archivematica-msgcreator"
      
  nextcloud:
    image: "nextcloud"
    build:
      context: "../src/rdss-arkivum-nextcloud/"
