---
version: "2"

services:

  # Applies SSL as a proxy in front of the Shibboleth SP proxy
  nginx-ssl:
    image: "arkivum/nginx-ssl"
    build:
      context: "./am-shib/nginx-ssl/"
    networks:
      default:
          aliases:
            - "dashboard.archivematica.${DOMAIN_NAME}"
            - "ss.archivematica.${DOMAIN_NAME}"
      shibnet:
          aliases:
            - "dashboard.archivematica.${DOMAIN_NAME}"
            - "ss.archivematica.${DOMAIN_NAME}"
    ports:
      - "${NGINX_EXTERNAL_IP}:${AM_EXTERNAL_PORT}:443"
    environment:
      AM_DASHBOARD_HOST: "dashboard.archivematica.${DOMAIN_NAME}"
      AM_STORAGE_SERVICE_HOST: "ss.archivematica.${DOMAIN_NAME}"
      AM_EXTERNAL_PORT:
      SHIB_SP_HOST: "shib-sp-proxy"
    volumes:
      - "${VOL_BASE}/am-shib/build/secrets/:/secrets/:ro"
    depends_on:
      - "shib-sp-proxy"

  # Enforces Shibboleth authentication in front of our AM nginx proxy
  shib-sp-proxy:
    image: "rdss-archivematica-shib-sp-proxy"
    #build:
    #  context: "${VOL_BASE}/../src/rdss-archivematica-shib-sp-proxy/"
    networks:
      default:
      shibnet:
    environment:
      # Target proxy (our nginx container)
      TARGET_PROXY_HOST: "nginx"
      # Archivematica
      AM_DASHBOARD_HOST: "dashboard.archivematica.${DOMAIN_NAME}"
      AM_DASHBOARD_SSL_CA_BUNDLE_FILE: "/secrets/sp-proxy/sp-ca-bundle.pem"
      AM_DASHBOARD_SSL_CERT_FILE: "/secrets/sp-proxy/sp-am-dash-cert.pem"
      AM_DASHBOARD_SSL_KEY_FILE: "/secrets/sp-proxy/sp-am-dash-key.pem"
      AM_DASHBOARD_TARGET_PORT: "80"
      AM_STORAGE_SERVICE_HOST: "ss.archivematica.${DOMAIN_NAME}"
      AM_STORAGE_SERVICE_SSL_CA_BUNDLE_FILE: "/secrets/sp-proxy/sp-ca-bundle.pem"
      AM_STORAGE_SERVICE_SSL_CERT_FILE: "/secrets/sp-proxy/sp-am-ss-cert.pem"
      AM_STORAGE_SERVICE_SSL_KEY_FILE: "/secrets/sp-proxy/sp-am-ss-key.pem"
      AM_STORAGE_SERVICE_TARGET_PORT: "8000"
      AM_EXTERNAL_PORT:
      # Shibboleth FastCGI SP config
      SHIBBOLETH_IDP_ENTITY_ID: "https://idp.${DOMAIN_NAME}/idp/shibboleth"
      SHIBBOLETH_IDP_METADATA_URL: "https://idp.${DOMAIN_NAME}:${IDP_EXTERNAL_PORT}/idp/shibboleth"
      # Metadata config - set URL subst to same as IdP metadata URL for our local IDP
      SHIBBOLETH_METADATA_SIGNING_CERT: "/etc/shibboleth/md-signing.crt"
      SHIBBOLETH_METADATA_URL_SUBST: "https://idp.${DOMAIN_NAME}:${IDP_EXTERNAL_PORT}/idp/shibboleth"
      # Error support contact
      SHIBBOLETH_SUPPORT_EMAIL: "shibboleth-support@${DOMAIN_NAME}"
    volumes:
      - "${VOL_BASE}/am-shib/build/secrets/:/secrets/:ro"
      - "${VOL_BASE}/shib-local/build/secrets/idp/idp.${DOMAIN_NAME}.crt:/etc/shibboleth/md-signing.crt:ro"
    depends_on:
      - "nginx"

  archivematica-dashboard:
    environment:
      ARCHIVEMATICA_DASHBOARD_SHIBBOLETH_AUTHENTICATION: "True"

  archivematica-storage-service:
    environment:
      SS_SHIBBOLETH_AUTHENTICATION: "True"

networks:
  shibnet:
    driver: "bridge"