---
version: "2"

volumes:

  mysql_data:
  elasticsearch_data:
  archivematica_pipeline_data:
  archivematica_storage_service_staging_data:

services:

  minio:
    image: "minio/minio:latest"
    command: "server /export"
    environment:
      MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
      MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    volumes:
      - "./etc/minio:/root/.minio"
      - "./s3:/export"
    ports:
      - "9000"
    expose:
      - "9000"

  mysql:
    image: "percona:5.6"
    user: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - "mysql_data:/var/lib/mysql"
    expose:
      - "3306"

  elasticsearch:
    image: "elasticsearch:1.7-alpine"
    command: "elasticsearch -Des.node.name=TestNode -Des.network.host=0.0.0.0"
    privileged: yes
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    expose:
      - "9200"

  redis:
    image: "redis:3.2-alpine"
    command: '--save "" --appendonly no'  # Persistency disabled
    user: "redis"
    expose:
      - "6379"

  gearmand:
    image: "artefactual/gearmand:1.1.15-alpine"
    command: "--queue-type=redis --redis-server=redis --redis-port=6379"
    user: "gearman"
    expose:
      - "4730"
    links:
      - "redis"

  fits:
    image: "artefactual/fits-ngserver:0.8.4"
    expose:
      - "2113"
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"

  clamavd:
    image: "dinkel/clamavd:latest"
    expose:
      - "3310"
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"

  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/nginx/archivematica.conf:/etc/nginx/conf.d/archivematica.conf:ro"
    expose:
      - "80"
      - "8000"
    ports:
      - "80"
      - "8000"

  dynalite:
    build:
      context: "../../src/rdss-archivematica-channel-adapter/hack/minikine"
      dockerfile: "dynalite.Dockerfile"
    ports:
      - "4567"
    expose:
      - "4567"

  minikine:
    build:
      context: "../../src/rdss-archivematica-channel-adapter/hack/minikine"
      dockerfile: "minikine.Dockerfile"
    environment:
      MINIKINE_STREAM_MAIN: "main"
      MINIKINE_STREAM_INVALID: "invalid"
      MINIKINE_STREAM_ERROR: "error"
      MINIKINE_STREAM_SHARDS: "4"
    ports:
      - "4567"
    expose:
      - "4567"

  archivematica-mcp-server:
    build:
      context: "../../src/archivematica/src"
      dockerfile: "MCPServer.Dockerfile"
    environment:
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.common"
      ARCHIVEMATICA_MCPSERVER_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_MCPSERVER_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_MCPSERVER_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_MCPARCHIVEMATICASERVER: "gearmand:4730"
    volumes:
      - "../../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../../src/archivematica/src/dashboard/:/src/dashboard/"
      - "../../src/archivematica/src/MCPServer/:/src/MCPServer/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"

  archivematica-mcp-client:
    build:
      context: "../../src/archivematica/src"
      dockerfile: "MCPClient.Dockerfile"
    environment:
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.common"
      NAILGUN_SERVER: "fits"
      NAILGUN_PORT: "2113"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ARCHIVEMATICACLIENTMODULES: "/src/MCPClient/lib/archivematicaClientModules"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLIENTSCRIPTSDIRECTORY: "/src/MCPClient/lib/clientScripts/"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER: "elasticsearch:9200"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_MCPARCHIVEMATICASERVER: "gearmand:4730"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER: "clamavd:3310"
    volumes:
      - "../../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../../src/archivematica/src/dashboard/:/src/dashboard/"
      - "../../src/archivematica/src/MCPClient/:/src/MCPClient/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "fits"
      - "clamavd"
      - "mysql"
      - "gearmand"
      - "elasticsearch"
      - "archivematica-storage-service"

  archivematica-dashboard:
    build:
      context: "../../src/archivematica/src"
      dockerfile: "dashboard.Dockerfile"
    environment:
      FORWARDED_ALLOW_IPS: "*"  # Specific to Gunicorn
      DJANGO_SETTINGS_MODULE: "settings.local"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_SECRET_KEY: "12345"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_ALLOWED_HOSTS: "*"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_GEARMAN_SERVER: "gearmand:4730"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER: "elasticsearch:93200"
      ARCHIVEMATICA_DASHBOARD_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_DASHBOARD_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE: "MCP"
    volumes:
      - "../../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../../src/archivematica/src/dashboard/:/src/dashboard/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    expose:
      - "8000"
    links:
      - "mysql"
      - "gearmand"
      - "elasticsearch"
      - "archivematica-storage-service"

  archivematica-storage-service:
    build:
      context: "../../src/archivematica-storage-service"
    environment:
      FORWARDED_ALLOW_IPS: "*"  # Specific to Gunicorn
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "storage_service.settings.local"
      DJANGO_ALLOWED_HOSTS: "*"
      SS_DB_URL: "mysql://archivematica:demo@mysql/SS"
    volumes:
      - "../../src/archivematica-storage-service/:/src/"
      - "../../src/archivematica-sampledata/:/home/archivematica-sampledata/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
    expose:
      - "8000"
    links:
      - "mysql"

  rdss-archivematica-channel-adapter-consumer:
    build:
      context: "../../src/rdss-archivematica-channel-adapter"
    entrypoint: "go run main.go consumer"
    environment:
      RDSS_ARCHIVEMATICA_ADAPTER_LOGGING.LEVEL: "debug"
      RDSS_ARCHIVEMATICA_ADAPTER_AMCLIENT.URL: "http://archivematica-dashboard:8000"
      RDSS_ARCHIVEMATICA_ADAPTER_AMCLIENT.USER: "test"
      RDSS_ARCHIVEMATICA_ADAPTER_AMCLIENT.KEY: "test"
      RDSS_ARCHIVEMATICA_ADAPTER_S3.ENDPOINT: "http://minio:9000"
      RDSS_ARCHIVEMATICA_ADAPTER_S3.FORCE_PATH_STYLE: "true"
      RDSS_ARCHIVEMATICA_ADAPTER_S3.INSECURE_SKIP_VERIFY: "true"
      RDSS_ARCHIVEMATICA_ADAPTER_S3.ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
      RDSS_ARCHIVEMATICA_ADAPTER_S3.SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      RDSS_ARCHIVEMATICA_ADAPTER_S3.REGION: "eu-west-2"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.QUEUES.MAIN: "main"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.QUEUES.INVALID: "invalid"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.QUEUES.ERROR: "error"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.BACKEND: "kinesis"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.KINESIS.TLS: "false"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.KINESIS.ENDPOINT: "http://minikine:4567"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.KINESIS.TLS_DYNAMODB: "false"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.KINESIS.ENDPOINT_DYNAMODB: "http://dynalite:4567"
      AWS_REGION: "kinalite-does-not-care"
      AWS_ACCESS_KEY: "kinesis-does-not-care"
      AWS_SECRET_KEY: "kinesis-does-not-care"
    links:
      - "archivematica-dashboard"
      - "minikine"
      - "dynalite"
    volumes:
      - "../../src/rdss-archivematica-channel-adapter:/go/src/github.com/JiscRDSS/rdss-archivematica-channel-adapter"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    ports:
      - "6060" # See net/http/pprof

  rdss-archivematica-channel-adapter-publisher:
    build:
      context: "../../src/rdss-archivematica-channel-adapter"
    entrypoint: "go run main.go publisher"
    environment:
      RDSS_ARCHIVEMATICA_ADAPTER_LOGGING.LEVEL: "debug"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.QUEUES.MAIN: "main"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.QUEUES.INVALID: "invalid"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.QUEUES.ERROR: "error"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.BACKEND: "kinesis"
      RDSS_ARCHIVEMATICA_ADAPTER_BROKER.KINESIS.ENDPOINT: "http://minikine:4567"
      AWS_REGION: "kinalite-does-not-care"
      AWS_ACCESS_KEY: "kinesis-does-not-care"
      AWS_SECRET_KEY: "kinesis-does-not-care"
    links:
      - "archivematica-dashboard"
      - "minikine"
    volumes:
      - "../../src/rdss-archivematica-channel-adapter:/go/src/github.com/JiscRDSS/rdss-archivematica-channel-adapter"
    ports:
      - "6060" # See net/http/pprof

