---
version: "2"

volumes:

  mysql_data:
  elasticsearch_data:
  archivematica_pipeline_data:
  archivematica_storage_service_data:
  archivematica_storage_service_staging_data:

services:

  mysql:
    image: "percona:5.6"
    user: "mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=12345"
    volumes:
      - "mysql_data:/var/lib/mysql"
    expose:
      - "3306"

  elasticsearch:
    image: "elasticsearch:1.7-alpine"
    command: "elasticsearch -Des.node.name=TestNode -Des.network.host=0.0.0.0"
    privileged: yes
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    expose:
      - "9200"

  redis:
    image: "redis:3.2-alpine"
    command: '--save "" --appendonly no'  # Persistency disabled
    user: "redis"
    expose:
      - "6379"

  gearmand:
    image: "artefactual/gearmand:1.1.15-alpine"
    command: "--queue-type=redis --redis-server=redis --redis-port=6379"
    user: "gearman"
    expose:
      - "4730"
    links:
      - "redis"

  clamavd:
    image: "dinkel/clamavd:latest"
    expose:
      - "3310"

  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    expose:
      - "80"
      - "8000"
    ports:
      - "80"
      - "8000"

  archivematica-mcp-server:
    build:
      context: "../../src/archivematica/src"
      dockerfile: "MCPServer.Dockerfile"
    environment:
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.local"
    volumes:
      - "../../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../../src/archivematica/src/dashboard/:/src/dashboard/"
      - "../../src/archivematica/src/MCPServer/:/src/MCPServer/"
      - "./etc/archivematica/archivematicaCommon/dbsettings:/etc/archivematica/archivematicaCommon/dbsettings:ro"
      - "./etc/archivematica/MCPServer/serverConfig.conf:/etc/archivematica/MCPServer/serverConfig.conf:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"

  archivematica-mcp-client:
    build:
      context: "../../src/archivematica/src"
      dockerfile: "MCPClient.Dockerfile"
    environment:
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.local"
    volumes:
      - "../../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../../src/archivematica/src/dashboard/:/src/dashboard/"
      - "../../src/archivematica/src/MCPClient/:/src/MCPClient/"
      - "./etc/archivematica/archivematicaCommon/dbsettings:/etc/archivematica/archivematicaCommon/dbsettings:ro"
      - "./etc/archivematica/MCPClient/clientConfig.conf:/etc/archivematica/MCPClient/clientConfig.conf:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"
      - "elasticsearch"
      - "archivematica-storage-service"

  archivematica-dashboard:
    build:
      context: "../../src/archivematica/src"
      dockerfile: "dashboard.Dockerfile"
    environment:
      FORWARDED_ALLOW_IPS: "*"  # Specific to Gunicorn
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.local"
      ARCHIVEMATICA_DASHBOARD_GEARMAN: "gearmand:4730"
    volumes:
      - "../../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../../src/archivematica/src/dashboard/:/src/dashboard/"
      - "./etc/archivematica/archivematicaCommon/dbsettings:/etc/archivematica/archivematicaCommon/dbsettings:ro"
      - "./etc/archivematica/MCPClient/clientConfig.conf:/etc/archivematica/MCPClient/clientConfig.conf:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    expose:
      - "8000"
    links:
      - "mysql"
      - "gearmand"
      - "elasticsearch"
      - "archivematica-storage-service"

  archivematica-storage-service:
    build:
      context: "../../src/archivematica-storage-service"
    environment:
      FORWARDED_ALLOW_IPS: "*"  # Specific to Gunicorn
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "storage_service.settings.local"
      SS_DB_URL: "mysql://archivematica:demo@mysql/SS"
    volumes:
      - "../../src/archivematica-storage-service/:/src/"
      - "../../src/archivematica-sampledata/:/home/archivematica-sampledata/"
      - "archivematica_storage_service_data:/var/archivematica/sharedDirectory:rw"
      - "archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
    expose:
      - "8000"
    links:
      - "mysql"
